AllCops:
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - db/schema.rb
    - app/controllers/application_controller.rb
    - 'db/**/*'
Documentation:
    Enabled: false
LineLength:
    Enabled: false